name: Paper Jacket Creative
favicon: null
layout_spectrum: 0.3868385422974825
typography_spectrum: 0.71214610314928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.04371115216054022
  lightness: 0.12805719627067447
  saturation: 0.7852274705655873
  rhythmicContrast: 0.5028749802149832
purpose: []
